[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "edmt"
version = "1.0.2dev"
description = "Environmental Data Management Toolbox"
readme = "README.md"
requires-python = ">=3.10"
license = {file = "LICENSE"} 
authors = [
  {name = "Odero, Kuloba & musasia", email = "francisodero10@gmail.com"},
]
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent"
]

dependencies = [
  "duckdb",
  "earthengine-api>=0.1.324,<1.7.10",
  "google-api-core>=2.17,<3.0.0",
  "google-auth>=2.20,<2.48",
  "geopandas>=0.12.2,<1.1",
  "fiona>=1.9.6",
  "tqdm>=4",
  "requests"
]

[project.urls]
Homepage = "https://github.com/envdmt/EDMT/"

[project.scripts]
edmt = "edmt.cli:main"

[tool.setuptools.packages.find]
include = ["edmt*"]
