[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "edmt"
version = "1.0.2dev"
description = "Environmental Data Management Toolbox"
readme = "README.md"
requires-python = ">=3.10"
license = {file = "LICENSE"} 
authors = [
  {name = "Odero, Kuloba & musasia", email = "francisodero10@gmail.com"},
]
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent"
]

dependencies = [
  "duckdb",
  "contourpy>=1.2.1",
  "earthengine-api>=0.1.324,<1.7.10",
  "google-api-core>=2.11,<2.15",
  "google-auth>=2.20,<2.48",
  "google-auth-httplib2>=0.1.0,<0.2",
  "google-api-python-client>=2.86,<2.95",
  "pillow>=10.4,<11",
  "geopandas>=0.12.2,<1.1",
  "mapclassify>=2.8,<2.10",
  "fiona>=1.9.6",
  "folium>=0.18.0",
  "plotly>=5.24.1",
  "seaborn>=0.13.2",
  "tqdm>=4",
  "requests"
]

[project.urls]
Homepage = "https://github.com/envdmt/EDMT/"

[project.scripts]
edmt = "edmt.cli:main"

[tool.setuptools.packages.find]
include = ["edmt*"]
